name: Deploy Node.js to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --only=production
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_46EA752DBDAA45FBA4C9BDD62F6D7D21 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_73E9E01567274685AD7D8A55534B7098 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C15389F600834320848DF9370ACBA4AE }}
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'microfinance-backend-api'
        package: '.'
        startup-command: 'node app.js'